In [152]:
#import numpy
import numpy as np
import pandas as pd

## Numpy Data types

In [2]:
# Declaring 1 dimension array using numpy
a1 = np.array([3,5,3])

In [9]:
#declaring 2x3 dimesnional array
a2 = np.array([[3.9,4,5],[3,4,5]])

In [6]:
#printing arrays
a1

array([3, 5, 3])

In [31]:
#checking shape of an array
a2.shape

(2, 3)

In [26]:
a3 = np.array([[[2,3,4],[3,4,5],[3,4,5] ],
    [ [2,3,4],[3,4,5],[3,4,5] ],
    [ [2,3,4],[3,4,5],[3,4,5] ]
              ])

In [27]:
#checking dimension of an array
a3.ndim

3

In [30]:
a3.shape

(3, 3, 3)

In [8]:
#priting array data types
a1.dtype

dtype('int32')

In [11]:
a2.dtype

dtype('float64')

In [14]:
#printing number of elements in array
a1.size

3

In [15]:
a2.size

6

In [17]:
#Printing dimesnions of array
a1.ndim

1

In [18]:
a2.ndim

2

## Creating numpy arrays

In [33]:
# creating array for ones
ones = np.ones((3,4))

In [34]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
#creating array for zeros
zeros = np.zeros((4,5))

In [39]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
# defining int arrays randomly
random_int_array = np.random.randint(0,10,[3,4])

In [47]:
random_int_array

array([[2, 9, 2, 1],
       [5, 9, 8, 4],
       [6, 1, 3, 8]])

In [49]:
# defining float arrays randomly
random_float_array = np.random.random((3,5))

In [50]:
random_float_array

array([[0.28238332, 0.95462353, 0.61309343, 0.5900584 , 0.29286005],
       [0.19011839, 0.78697042, 0.92965804, 0.6766306 , 0.4058793 ],
       [0.06066548, 0.74485125, 0.26779918, 0.85282468, 0.34745609]])

In [54]:
# defining random array from a range
array_from_range = np.arange(3,5,0.3)

In [52]:
array_from_range

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6. , 6.3, 6.6, 6.9, 7.2, 7.5,
       7.8, 8.1, 8.4, 8.7, 9. , 9.3, 9.6, 9.9])

In [64]:
#generate random numbers using seed function meaning it would help generate same numbers each time
np.random.seed(0)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [70]:
random_array_5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [74]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.15896958, 0.11037514, 0.65632959],
       [0.13818295, 0.19658236, 0.36872517],
       [0.82099323, 0.09710128, 0.83794491],
       [0.09609841, 0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552, 0.73926358]])

## Viweing and slicing numpy arrays

In [75]:
random_array_1 = np.random.randint(10,size=(5,3))

In [76]:
random_array_1

array([[0, 2, 7],
       [2, 9, 2],
       [3, 3, 2],
       [3, 4, 1],
       [2, 9, 1]])

In [77]:
#finding unique number in random_array_1
np.unique(random_array_1)

array([0, 1, 2, 3, 4, 7, 9])

In [78]:
random_array_1[:]

array([[0, 2, 7],
       [2, 9, 2],
       [3, 3, 2],
       [3, 4, 1],
       [2, 9, 1]])

In [79]:
random_array_1[:2]

array([[0, 2, 7],
       [2, 9, 2]])

In [80]:
random_array_1[:,:2]

array([[0, 2],
       [2, 9],
       [3, 3],
       [3, 4],
       [2, 9]])

In [81]:
random_array_1[:2,:3]

array([[0, 2, 7],
       [2, 9, 2]])

In [82]:
#now let's define a rather deep array
random_array_2 = np.random.randint(10,size=(3,3,3))

In [83]:
random_array_2

array([[[4, 6, 8],
        [2, 3, 0],
        [0, 6, 0]],

       [[6, 3, 3],
        [8, 8, 8],
        [2, 3, 2]],

       [[0, 8, 8],
        [3, 8, 2],
        [8, 4, 3]]])

In [85]:
random_array_2.shape

(3, 3, 3)

In [92]:
# we are extracting 6,3 from 2nd matrix having first row and having first 2 column
random_array_2[1:2,0:1,0:2]

array([[[6, 3]]])

## Manipulating and comparing arrays

### Arithmetic orperation

In [99]:
# create an array
aa1 = np.array([[1],[3],[4],[4]])

In [108]:
#Create array with ones
aa2 = np.ones((4,1))

In [103]:
aa1 + aa2

array([[2., 2.],
       [4., 4.],
       [5., 5.],
       [5., 5.]])

In [104]:
aa1 - aa2

array([[0., 0.],
       [2., 2.],
       [3., 3.],
       [3., 3.]])

In [110]:
aa1 + aa2

array([[2.],
       [4.],
       [5.],
       [5.]])

In [118]:
#calculating time difference between python function and numpy sum function
cal_array = np.ones((10000))
%timeit sum(cal_array) # calculating sum using python function
%timeit np.sum(cal_array)

2.33 ms ± 228 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
12.1 µs ± 587 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Reshape and transpote

In [135]:
arr1 = np.random.randint(10, size=(5,4))
arr1

array([[0, 3, 8, 7],
       [7, 1, 8, 4],
       [7, 0, 4, 9],
       [0, 6, 4, 2],
       [4, 6, 3, 3]])

In [136]:
arr2 = np.random.randint(10,size=(3,5,1))
arr2

array([[[7],
        [8],
        [5],
        [0],
        [8]],

       [[5],
        [4],
        [7],
        [4],
        [1]],

       [[3],
        [3],
        [9],
        [2],
        [5]]])

In [137]:
arr1 * arr2

array([[[ 0, 21, 56, 49],
        [56,  8, 64, 32],
        [35,  0, 20, 45],
        [ 0,  0,  0,  0],
        [32, 48, 24, 24]],

       [[ 0, 15, 40, 35],
        [28,  4, 32, 16],
        [49,  0, 28, 63],
        [ 0, 24, 16,  8],
        [ 4,  6,  3,  3]],

       [[ 0,  9, 24, 21],
        [21,  3, 24, 12],
        [63,  0, 36, 81],
        [ 0, 12,  8,  4],
        [20, 30, 15, 15]]])

In [138]:
arr1

array([[0, 3, 8, 7],
       [7, 1, 8, 4],
       [7, 0, 4, 9],
       [0, 6, 4, 2],
       [4, 6, 3, 3]])

In [141]:
arr1.shape

(5, 4)

In [149]:
arr1.T.shape

(4, 5)

In [148]:
arr1

array([[0, 3, 8, 7],
       [7, 1, 8, 4],
       [7, 0, 4, 9],
       [0, 6, 4, 2],
       [4, 6, 3, 3]])

## An excercise for implementing a excel sheet data using pandas and numpy

In [151]:
sales_data = np.random.randint(10, size=(5,3))
sales_data

array([[2, 3, 5],
       [7, 2, 7],
       [1, 6, 5],
       [0, 0, 3],
       [1, 9, 9]])

In [155]:
sales_data_frame = pd.DataFrame(sales_data, columns=["Almond butter", "Peanut butter", "Cashew butter"],
                               index=["Mon","Tues","Wed","Thu","Fri"])

In [156]:
sales_data_frame

Almond butter  Peanut butter  Cashew butter
Mon               2              3              5
Tues              7              2              7
Wed               1              6              5
Thu               0              0              3
Fri               1              9              9

In [157]:
sales_prices = np.random.randint(10, size=(1,3))

In [158]:
sales_prices

array([[6, 6, 7]])

In [159]:
sales_prices_frame = pd.DataFrame(sales_prices, index=["price"], columns=["Almond butter", "Peanut butter", "Cashew butter"])

In [161]:
sales_prices_frame

Almond butter  Peanut butter  Cashew butter
price              6              6              7

In [162]:
sales_data.shape

(5, 3)

In [164]:
sales_prices.shape

(1, 3)

In [165]:
total = sales_prices.dot(sales_data.T)

In [166]:
total

array([[ 65, 103,  77,  21, 123]])

In [167]:
sales_data_frame["Total($)"] = total.T

In [168]:
sales_data_frame

Almond butter  Peanut butter  Cashew butter  Total($)
Mon               2              3              5        65
Tues              7              2              7       103
Wed               1              6              5        77
Thu               0              0              3        21
Fri               1              9              9       123

In [169]:
sales_prices

array([[6, 6, 7]])

In [170]:
sales_prices > 5

array([[ True,  True,  True]])

In [171]:
sales_prices < 5

array([[False, False, False]])

## Sorting numpy Arrays

In [182]:
random_array = np.random.randint(10, size=(3,3))

In [183]:
random_array

array([[2, 7, 8],
       [4, 4, 1],
       [7, 6, 9]])

In [185]:
#sort across row if axis = 1 then it will be across column
random_array.sort(axis = 0)
random_array

array([[2, 4, 1],
       [4, 6, 8],
       [7, 7, 9]])

In [186]:
#sort using argsort basically what it does is show that which index values should shift where if sorted
np.argsort(random_array)

array([[2, 0, 1],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [189]:
random_array_2 = np.random.randint(10,size=(1,4))

In [190]:
random_array_2

array([[7, 1, 3, 5]])

In [191]:
np.argsort(random_array_2)

array([[1, 2, 3, 0]], dtype=int64)

## Numpy in action using Images 

<img src="panda.png">

In [193]:
#importing imread function from matplotlib
from matplotlib.image import imread

In [194]:
panda = imread("panda.png")

In [195]:
type(panda)

numpy.ndarray

In [201]:
panda[:3,:3,:3]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667]]], dtype=float32)

In [197]:
panda.shape

(2330, 3500, 3)

<img src="car-photo.png">

In [204]:

car = imread("car-photo.png")

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352